name: build
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "pnpm"
      - run: pnpm install --frozen-lockfile
        
      - name: run tests on node 20
        run: pnpm run test
      
      - uses: actions/setup-node@v3
        with:
          node-version: 21
      - name: run tests on node 21
        run: pnpm run test